backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
  branch: master # Branch to update (master by default)

media_folder: "themes/dealfinder/static/img" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded media will begin with

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: "accueil"
        label: "Page d'accueil"
        file: "content/_index.md"
        description: "Texte de votre page d'accueil"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text"}
          - {label: "Image - Partage Réseaux Sociaux", name: "image", widget: "image", required: false, hint: "Recommended size is 1200px x 630px"}
          - name: sectionSlider
            label: Section Slider
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Bouton gauche" 
                name: "btn1" 
                widget: "object" 
                fields:
                  - {label: "Texte", name: "text", widget: "string"}
                  - {label: "Lien", name: "link", widget: "string"}
              - label: "Bouton droite" 
                name: "btn2" 
                widget: "object" 
                fields:
                  - {label: "Texte", name: "text", widget: "string"}
                  - {label: "Lien", name: "link", widget: "string"}
              - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image de 1100px par 637px."}
          - name: sectionFonctionnalites
            label: Section Fonctionnalites
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - name: points
                label: "Fonctionnalités"
                widget: list
                allow_add: false
                fields:
                  - {label: "Icône", name: "icon", widget: "string"}
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
          - name: sectionBudget
            label: Section Budget
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - name: notes
                label: Notes
                widget: list
                allow_add: true
                fields:
                  - {label: "Texte", name: "text", widget: "string"}
              - name: Profils
                label: profiles
                widget: list
                allow_add: true
                fields:
                  - {label: "Icône", name: "icon", widget: "string"}
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image d'environ 500px par 400px."}
          - name: sectionAbout
            label: Section À Propos
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - name: points
                label: Points notables
                widget: list
                allow_add: true
                fields:
                  - {label: "Texte", name: "text", widget: "string"}
              - {label: "Veux-tu un vidéo?", name: "wantVideo", widget: "boolean", required: false, default: false, hint: "Si cette case est cochée, un vidéo sera utilisé. SVP remplir le champ suivant 'Image/Vidéo' en fonction de votre choix."}
              - {label: "Image/Vidéo", name: "image", widget: "image"}
          - name: sectionHiw
            label: "Section Comment Ça Marche"
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - name: points
                label: "Fonctionnement de la plateforme"
                widget: list
                allow_add: true
                fields:
                  - {label: "Icône", name: "icon", widget: "string"}
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image de 1100px par 637px."}
          - name: sectionTestimonials
            label: "Section Témoignages"
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - name: points
                label: "Témoignages"
                widget: list
                allow_add: true
                fields:
                  - {label: "Nom", name: "name", widget: "string"}
                  - {label: "Témoignage", name: "description", widget: "string"}
                  - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image de 250px par 250px."}
          - name: sectionContact
            label: Section Contact
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Boite de gauche - Ligne 1", name: "tagline1", widget: "text"}
              - {label: "Boite de gauche - Ligne 2", name: "tagline2", widget: "text"}
          - name: sectionClient
            label: Section Client
            widget: object
            fields:
              - name: clients
                label: "Logos de clients"
                widget: list
                allow_add: false
                fields:
                  - {label: "Lien vers leur site", name: "link", widget: "string"}
                  - {label: "Logo", name: "logo", widget: "image", hint: "Utilisez un PNG de 150px de large, avec fond transparent."}
          - name: sectionCta
            label: Section Call To Action
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Bouton gauche" 
                name: "btn" 
                widget: "object" 
                fields:
                  - {label: "Texte", name: "text", widget: "string"}
                  - {label: "Lien", name: "link", widget: "string"}
      - name: "politique-confidentialite"
        label: "Politique de confidentialité"
        file: "content/singles/politique-confidentialite.md"
        description: "Texte de votre politique de confidentialité"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text"}
          - {label: "Image - Partage Réseaux Sociaux", name: "image", widget: "image", required: false, hint: "Recommended size is 1200px x 630px"}
          - {label: "Slug/Link", name: "slug", widget: "hidden", default: "politique-de-confidentialite", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
          - {label: "Layout", name: "layout", widget: "hidden", default: "general"}
          - {label: "Texte", name: "body", widget: "markdown"}
      - name: "conditions-d-utilisation"
        label: "Conditions d'utilisation"
        file: "content/singles/conditions-utilisation.md"
        description: "Texte de vos conditions d'utilisation"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text"}
          - {label: "Image - Partage Réseaux Sociaux", name: "image", widget: "image", required: false, hint: "Recommended size is 1200px x 630px"}
          - {label: "Slug/Link", name: "slug", widget: "hidden", default: "conditions-d-utilisation", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
          - {label: "Layout", name: "layout", widget: "hidden", default: "general"}
          - {label: "Texte", name: "body", widget: "markdown"}
##### SETTINGS
  - name: "autres"
    label: "Autres"
    editor:
      preview: false
    files:
      - name: "menu"
        label: "Menu"
        file: "data/menu.yml"
        description: "Menu"
        fields:
          - name: main
            label: Menu principal
            widget: list
            allow_add: false
            fields:
              - {label: "Texte", name: "fr", widget: "string"}
              - {label: "Lien", name: "link", widget: "hidden"}
              - {label: "Sous-menu", name: "submenu", widget: "boolean"}
              - name: links
                label: Liens
                widget: list
                allow_add: false
                fields:
                  - {label: "Texte", name: "fr", widget: "string"}
                  - {label: "Lien", name: "link", widget: "hidden"}
      - name: "settings"
        label: "Généralités"
        file: "data/settings.yml"
        description: "Généralités"
        fields:
          - name: socials
            label: Réseaux sociaux
            widget: object
            fields:
              - {label: "Facebook", name: "facebookurl", widget: "string"}
              - {label: "Linkedin", name: "linkedinurl", widget: "string", required: false}
              - {label: "Twitter", name: "twitterurl", widget: "string", required: false}
              - {label: "Youtube", name: "youtubeurl", widget: "string", required: false}
              - {label: "Instagram", name: "instagramurl", widget: "string", required: false}
          - name: address
            label: Adresse
            widget: object
            fields:
              - {label: "Rue", name: "road", widget: "string"}
              - {label: "Appartement", name: "app", widget: "string", required: false}
              - {label: "Ville", name: "city", widget: "string"}
              - {label: "Province", name: "province", widget: "string"}
              - {label: "Code postal", name: "postal", widget: "string"}
              - {label: "Pays", name: "country", widget: "string"}
          - {label: "Téléphone", name: "phone", widget: "string"}
          - {label: "Téléphone (condensé)", name: "mphone", widget: "string"}
          - {label: "Courriel", name: "email", widget: "string"}
          - {name: sitedescription, label: "Description SEO par défaut", widget: "text", hint: "Ceci est la valeur pour la page d'accueil et la valeur par défaut pour toutes les pages."}
          - {name: sitetitle, label: "Titre SEO par défaut", widget: "string", hint: "Ceci est la valeur pour la page d'accueil et la valeur par défaut pour toutes les pages."}
          - {label: "Image de partage par défaut", name: "defaultsocialimage", widget: "image", hint: "Ceci est la valeur pour la page d'accueil et la valeur par défaut pour toutes les pages.", required: false}
          - {label: "Enlever des moteurs de recherche", name: "removefromexternalsearch", widget: "hidden", default: false, required: false}