backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
  branch: development # Branch to update (master by default)

media_folder: "themes/dealfinder/source-images" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded media will begin with

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: "accueil"
        label: "Page d'accueil"
        file: "content/_index.md"
        description: "Texte de votre page d'accueil"
        fields:
          - name: section1
            label: Section 1
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Bouton gauche" 
                name: "btn1" 
                widget: "object" 
                fields:
                  - {label: "Texte", name: "text", widget: "string"}
                  - {label: "Lien", name: "link", widget: "string"}
              - label: "Bouton droite" 
                name: "btn2" 
                widget: "object" 
                fields:
                  - {label: "Texte", name: "text", widget: "string"}
                  - {label: "Lien", name: "link", widget: "string"}
              - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image de 1100px par 637px."}
          - name: section2
            label: Section 2
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - name: points
                label: Points notables
                widget: list
                allow_add: true
                fields:
                  - {label: "Texte", name: "text", widget: "string"}
              - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image de 600px par 550px. Ça sort bien avec un GIF animé."}
          - name: section3
            label: Section 3
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - name: points
                label: "Fonctionnalités"
                widget: list
                allow_add: false
                fields:
                  - {label: "Icône", name: "icon", widget: "string"}
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
          - name: section4
            label: Section 4
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - name: points
                label: "Fonctionnement de la plateforme"
                widget: list
                allow_add: true
                fields:
                  - {label: "Icône", name: "icon", widget: "string"}
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image de 1100px par 637px."}
          - name: section5
            label: Section 5
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Boite de gauche - Ligne 1", name: "tagline1", widget: "text"}
              - {label: "Boite de gauche - Ligne 2", name: "tagline2", widget: "text"}
          - name: section6
            label: Section 6
            widget: object
            fields:
              - name: clients
                label: "Logos de clients"
                widget: list
                allow_add: false
                fields:
                  - {label: "Lien vers leur site", name: "link", widget: "string"}
                  - {label: "Logo", name: "logo", widget: "image", hint: "Utilisez un PNG de 150px de large, avec fond transparent."}
          - name: section7
            label: Section 7
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Bouton gauche" 
                name: "btn" 
                widget: "object" 
                fields:
                  - {label: "Texte", name: "text", widget: "string"}
                  - {label: "Lien", name: "link", widget: "string"}
##### SETTINGS
  - name: "autres"
    label: "Autres"
    editor:
      preview: false
    files:
      - name: "menu"
        label: "Menu"
        file: "data/menu.yml"
        description: "Menu"
        fields:
          - name: main
            label: Menu principal
            widget: list
            allow_add: false
            fields:
              - {label: "Texte", name: "fr", widget: "string"}
              - {label: "Lien", name: "link", widget: "hidden"}
              - {label: "Sous-menu", name: "submenu", widget: "boolean"}
              - name: links
                label: Liens
                widget: list
                allow_add: false
                fields:
                  - {label: "Texte", name: "fr", widget: "string"}
                  - {label: "Lien", name: "link", widget: "hidden"}